const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
    console.log('--- Cleaning Up Content ---');

    // 1. Delete Generated Lessons (Auto-generated by AI)
    // We keep VOCABULARY category as they are seeded/curated
    console.log("Deleting GENERATED lessons...");
    const deletedLessons = await prisma.lesson.deleteMany({
        where: { category: 'GENERATED' }
    });
    console.log(`Deleted ${deletedLessons.count} generated lessons.`);

    // 2. Delete Scenarios (Missions) - They will be re-seeded on next visit
    console.log("Deleting Scenarios...");
    // Must delete progress first
    await prisma.userScenarioProgress.deleteMany({});
    const deletedScenarios = await prisma.scenario.deleteMany({});
    console.log(`Deleted ${deletedScenarios.count} scenarios.`);

    // 3. Optional: Delete Chat History?
    // console.log("Deleting Chat History...");
    // await prisma.message.deleteMany({});
    // await prisma.conversation.deleteMany({});

    console.log("--- Cleanup Complete ---");
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
